import type { CampaignBrief } from './email';

export type DeliverableType =
  | 'social_post'
  | 'video'
  | 'print_ad'
  | 'billboard'
  | 'email_campaign'
  | 'landing_page'
  | 'experiential'
  | 'guerrilla'
  | 'podcast_ad'
  | 'influencer_collab'
  | 'twitter_thread'
  | 'reddit_ama'
  | 'tiktok_series'
  | 'blog_post';

export type Platform =
  | 'instagram'
  | 'tiktok'
  | 'linkedin'
  | 'twitter'
  | 'facebook'
  | 'youtube'
  | 'spotify'
  | 'print'
  | 'outdoor'
  | 'web'
  | 'email'
  | 'reddit'
  | 'discord'
  | 'newsletter'
  | 'pr'
  | 'app'
  | 'none';

export type DeliverableStatus =
  | 'not_started'
  | 'in_progress'
  | 'generation_failed'
  | 'ready_for_review'
  | 'approved'
  | 'needs_revision';

export type CampaignPhase =
  | 'concepting'    // Initial phase - assemble team, generate concepts
  | 'selecting'     // Choosing from generated concepts
  | 'generating'    // Auto-generating all deliverables
  | 'reviewing'     // Presentation review meeting
  | 'executing'     // All approved, ready to submit
  | 'submitted'     // Sent to client
  | 'completed';    // Client responded

export interface TeamMember {
  id: string;
  name: string;
  role: string;
  avatar: string;
  specialty: string;
  description: string;
  personality: string;
  voiceStyle: string;
}

export interface AssignedTeam {
  memberIds: string[];
  cost: number;
}

export interface GeneratedWork {
  id: string;
  content: string;
  preview?: string;
  imageUrl?: string;
  generatedAt: Date;
  revisionNumber: number;
  feedback?: string;
}

export interface Deliverable {
  id: string;
  type: DeliverableType;
  platform: Platform;
  description: string;
  creativeDirection?: string;
  assignedTeam: AssignedTeam | null;
  status: DeliverableStatus;
  productionCost: number;
  generatedWork: GeneratedWork | null;
  generationError?: string;
  suggested?: boolean; // Was this auto-suggested from the concept?
}

// Campaign Concept generated by AI
export interface CampaignConcept {
  id: string;
  name: string;
  tagline: string;
  bigIdea: string;
  recommendedChannels: string[];
  suggestedDeliverables: SuggestedDeliverable[];
  tone: string;
  whyItWorks: string;
  isTweaked?: boolean;
}

export interface SuggestedDeliverable {
  type: DeliverableType;
  platform: Platform;
  quantity: number;
  description: string;
}

export interface Campaign {
  id: string;
  briefId: string;
  clientName: string;
  campaignName: string;
  brief: CampaignBrief;
  // Budget system
  clientBudget: number;          // Total from client brief
  teamFee: number;               // Agency profit based on team size
  productionBudget: number;      // clientBudget - teamFee
  productionSpent: number;       // Sum of deliverable production costs
  startDate: Date;
  deadline: Date;
  phase: CampaignPhase;
  // Concepting phase
  conceptingTeam: AssignedTeam | null;
  strategicDirection: string;
  generatedConcepts: CampaignConcept[];
  selectedConceptId: string | null;
  // Execution phase
  deliverables: Deliverable[];
  productionTeam?: AssignedTeam | null;
  // Completion
  submittedAt?: Date;
  clientScore?: number;
  clientFeedback?: string;
  // Terminal tool integration
  toolsUsed?: string[];  // IDs of AgencyTools run against this campaign
}

// Team cost calculation - this is what you SPEND
export function calculateTeamCost(memberCount: number): number {
  switch (memberCount) {
    case 1: return 10000;
    case 2: return 25000;
    case 3: return 45000;
    case 4: return 70000;
    case 5: return 100000;
    case 6: return 135000;
    case 7: return 150000;
    default: return 0;
  }
}

// Production costs per deliverable type
export const PRODUCTION_COSTS: Record<DeliverableType, number> = {
  social_post: 5000,
  video: 22500,
  print_ad: 8000,
  billboard: 10000,
  email_campaign: 5000,
  landing_page: 12000,
  experiential: 15000,
  guerrilla: 8000,
  podcast_ad: 5000,
  influencer_collab: 10000,
  twitter_thread: 3000,
  reddit_ama: 3000,
  tiktok_series: 15000,
  blog_post: 4000,
};

export function getProductionCost(type: DeliverableType): number {
  return PRODUCTION_COSTS[type] || 5000;
}

// Deliverable type display names and icons
export const DELIVERABLE_TYPES: Record<DeliverableType, { label: string; icon: string }> = {
  social_post: { label: 'Social Post', icon: '📱' },
  video: { label: 'Video', icon: '🎬' },
  print_ad: { label: 'Print Ad', icon: '📰' },
  billboard: { label: 'Billboard', icon: '🏙️' },
  email_campaign: { label: 'Email Campaign', icon: '📧' },
  landing_page: { label: 'Landing Page', icon: '🌐' },
  experiential: { label: 'Experiential', icon: '🎪' },
  guerrilla: { label: 'Guerrilla', icon: '🎯' },
  podcast_ad: { label: 'Podcast Ad', icon: '🎙️' },
  influencer_collab: { label: 'Influencer Collab', icon: '🤝' },
  twitter_thread: { label: 'Twitter Thread', icon: '🧵' },
  reddit_ama: { label: 'Reddit AMA', icon: '💬' },
  tiktok_series: { label: 'TikTok Series', icon: '🎵' },
  blog_post: { label: 'Blog Post', icon: '📝' },
};

export const PLATFORMS: Record<Platform, { label: string; icon: string }> = {
  instagram: { label: 'Instagram', icon: '📸' },
  tiktok: { label: 'TikTok', icon: '🎵' },
  linkedin: { label: 'LinkedIn', icon: '💼' },
  twitter: { label: 'Twitter/X', icon: '🐦' },
  facebook: { label: 'Facebook', icon: '👥' },
  youtube: { label: 'YouTube', icon: '▶️' },
  spotify: { label: 'Spotify', icon: '🎧' },
  print: { label: 'Print', icon: '📄' },
  outdoor: { label: 'Outdoor', icon: '🏢' },
  web: { label: 'Web', icon: '🌐' },
  email: { label: 'Email', icon: '✉️' },
  reddit: { label: 'Reddit', icon: '🤖' },
  discord: { label: 'Discord', icon: '💬' },
  newsletter: { label: 'Newsletter', icon: '📨' },
  pr: { label: 'PR/Press', icon: '📰' },
  app: { label: 'Mobile App', icon: '📲' },
  none: { label: 'N/A', icon: '➖' },
};

export const STATUS_DISPLAY: Record<DeliverableStatus, { label: string; color: string }> = {
  not_started: { label: 'Not Started', color: '#9ca3af' },
  in_progress: { label: 'In Progress', color: '#a8d8ea' },
  generation_failed: { label: 'Failed', color: '#ef4444' },
  ready_for_review: { label: 'Ready for Review', color: '#f9e79f' },
  approved: { label: 'Approved', color: '#a8e6cf' },
  needs_revision: { label: 'Needs Revision', color: '#f4b8c5' },
};

// Format budget for display
export function formatBudget(amount: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    maximumFractionDigits: 0,
  }).format(amount);
}
